colin-kiegel/rust-derive-builder

- LICENSE-APACHE
- LICENSE-MIT
- Readme.md
Let's get this out of the way :)
@colin-kiegel, this is of course just a suggestion. MIT/Apache-2.0 is what most Rust libraries, incl. custom_derive, use.
> Add MIT/Apache2 License, Readme

- .travis.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- derive-builder-test/tests/generic_structs.rs
- derive-builder-test/tests/immutable.rs
- derive-builder-test/tests/multiple_derives.rs
- derive-builder-test/tests/mutable.rs
- derive-builder-test/tests/owned.rs
- derive-builder-test/tests/private_setters.rs
- derive-builder-test/tests/setter_prefix.rs
- src/lib.rs
- src/options.rs
Ok, here is my prototype for
- field specific overrides
- prefixed setters
My approach was to replace `struct OptionsBuilder` with `struct OptionsBuilder<Mode: OptionsBuilderMode>`
Obviously there is a struct mode and field mode: https://github.com/colin-kiegel/rust-derive-builder/blob/feature/field-overrides/src/options.rs#L87-L107
I then do this to get field specific overrides on the options defined for the struct
https://github.com/colin-kiegel/rust-derive-builder/blob/feature/field-overrides/src/lib.rs#L271-L273
The approach is optimized for basically identical options on struct and fields. As soon as we will get options specific to one of these modes, we need to introduce fields and impls on the ModeStructs itself.
PS: I just realized that I didn't need the phantom data, I could just …
> prefixed setters and field specific overrides

- derive_builder/CHANGELOG.md
- derive_builder/src/options/field_mode.rs
- derive_builder/src/options/mod.rs
- derive_builder/src/options/struct_mode.rs
- derive_builder/src/options/struct_options.rs
- derive_builder/tests/skip-setter.rs
- BEFORE: Unknown setter option `xkrz`.
- AFTER: Unknown setter option `xkrz` on field `foo`.
cc @killercup in case you want to give feedback. :-)
> better diagnostics on panics 

- derive_builder/CHANGELOG.md
- derive_builder/README.md
- derive_builder/examples/channel.rs
- derive_builder/examples/custom_defaults.rs
- derive_builder/examples/deny_missing_docs.rs
- derive_builder/examples/doc_example.rs
- derive_builder/examples/readme_example.rs
- derive_builder/src/lib.rs
- derive_builder/src/options/field_mode.rs
- derive_builder/src/options/field_options.rs
- derive_builder/src/options/mod.rs
- derive_builder/src/options/struct_mode.rs
- derive_builder/src/options/struct_options.rs
- derive_builder/tests/builder_name.rs
- derive_builder/tests/custom_default.rs
- derive_builder/tests/generic_structs.rs
- derive_builder/tests/setter_into.rs
- derive_builder/tests/setter_prefix.rs
- derive_builder/tests/setter_visibility.rs
- derive_builder/tests/skip-setter.rs
- derive_builder_core/src/setter.rs
This seems more idiomatic to me:
- setter conversions are now off by default, you can opt-into via `#[builder(setter(into))]`
=> breaking change — indeed I had to adapt a lot of testcases, which implicitly relied on generic setters.
cc @killercup in case you want to give feedback. :-)
---
PS: based on pr #57, so only the last commit is relevant here.
> opt into generic setters

- .travis.yml
- derive_builder/CHANGELOG.md
- derive_builder/Cargo.toml
- derive_builder/README.md
- derive_builder/build.rs
- derive_builder/src/lib.rs
- derive_builder/src/log_disabled.rs
- derive_builder_core/Cargo.toml
- derive_builder_core/src/lib.rs
- derive_builder_core/src/log_disabled.rs
- derive_builder_test/Cargo.toml
- put logging behind a feature flag to improve compile time,
since we have unit tests, this is far less important than before.
**Open Question**: I wonder how I should adapt the [travis configuration](https://github.com/colin-kiegel/rust-derive-builder/blob/feature/logging_optional/.travis.yml#L53-L55) to test for features.
- Would it be sufficient to just test `--features "compiletests logging"` on nightly?
- Or should I have one run with default features, and one with full features (except dev_nightly) on each rust release?
cc @killercup in case you want to give feedback. :-)
> feature flag `logging`

- derive_builder/CHANGELOG.md
- derive_builder/README.md
- derive_builder/src/lib.rs
- derive_builder/src/options/field_mode.rs
- derive_builder/src/options/macros.rs
- derive_builder/src/options/mod.rs
- derive_builder/src/options/struct_mode.rs
- derive_builder/src/options/struct_options.rs
- derive_builder_core/src/build_method.rs
- derive_builder_test/tests/run-pass/no_std.rs
cc @cramertj
This is work in progress and does not work yet.
open questions
- how do we tell cargo or travis that a certain test should only run on nightly rust? (#![feature(collections)] requires nightly)
- something **strange** happens with this code.
```rust
quote!(
#[cfg(not(no_std))]
#builder_vis fn build(#ref_self) -> ::std::result::Result<#struct_name #ty_generics, ::std::string::String> {
/* ... */
}
#[cfg(no_std)]
#builder_vis fn build(#ref_self) -> ::core::result::Result<#struct_name #ty_generics, ::collections::string::String> {
/* ... */
}
)
```
The expanded code _only_ contains the first part
```rust
#[cfg(not(no_std))]
#builder_vis fn build(#ref_self) -> ::std::result::Result<#struct_name #ty_generics, ::std::string::String> {
/* ... */
}
```
It's like the cfg-attributes …
> officially support `#![no_std]` #41

- derive_builder/src/doc_tpl/builder_struct.md
- derive_builder/src/options/mod.rs
Two minor things (both vaguely docs-related).
1. Made the builder's documentation include a link to the target type. Since we know we're in the same module as the target type, we can do this reliably with a relative URL.
1. Added a module-level doc comment to `derive_builder::options` to help others understand what's happening. @faern, let me know if this helps.
> Documentation-related enhancements

- derive_builder/CHANGELOG.md
- derive_builder/src/lib.rs
- derive_builder/src/options/struct_mode.rs
- derive_builder/src/options/struct_options.rs
- derive_builder/tests/bounds_generation.rs
- derive_builder_core/src/builder.rs
- derive_builder_core/src/options.rs
This addresses #91 for the `Clone` trait using the same principles as the built-in `#[derive(Clone)]` implementation. It's sitting on top of #85, so a diff against that branch may be more useful for seeing the scope of this change. 
@colin-kiegel, I'm not 100% happy with the split between `derive_builder` and `derive_builder_core` at the moment. The `StructOptions` has to pass some of the generics twice or else the generated code won't compile. At the moment that's easy to uphold, but I'm wondering if it would be better to pass `additional_bounds` to `derive_builder_core::Builder` and have it assemble the correct generics internally.
I deliberately didn't put anything about this in `README.md` - I think that the behavior after the PR is more "normal" than the current behavior, so trying …
> Improved type param bound expressions (#91)

- derive_builder/CHANGELOG.md
- derive_builder/Cargo.toml
- derive_builder/README.md
- derive_builder/src/lib.rs
- derive_builder/tests/compiletests.rs
- derive_builder/tests/run-pass/no_std.rs
- derive_builder_core/src/bindings.rs
- derive_builder_core/src/build_method.rs
- derive_builder_core/src/initializer.rs
As discussed in issue <https://github.com/colin-kiegel/rust-derive-builder/issues/107>
> Fix the build on master

- derive_builder/CHANGELOG.md
- derive_builder/tests/generic_with_default.rs
- derive_builder_core/src/build_method.rs
Fixes #127 for 0.5.2 without requiring the full update to 0.6.0
> Handle generics in build method struct default instantiation

- derive_builder/CHANGELOG.md
- derive_builder/src/options/darling_opts.rs
- derive_builder/tests/compile-fail/private_builder.rs
- derive_builder/tests/setter_visibility.rs
Declaring a builder public or private now overrides the struct's own visibility.
Fixes #99
> Honor struct-level builder visibility attributes

- derive_builder/CHANGELOG.md
- derive_builder/src/lib.rs
- derive_builder/src/options/darling_opts.rs
- derive_builder_core/src/builder.rs
Builders using the owned pattern for all fields don't need Clone derived for them,
and therefore can be used with generics that don't support cloning.
Fixes #97, and obviates #111 
@azriel91, please review this.
> Only derive Clone on builders when necessary

- derive_builder/CHANGELOG.md
- derive_builder/Cargo.toml
- derive_builder/src/lib.rs
- derive_builder/src/options/mod.rs
- derive_builder/tests/compile-fail/deny_empty_default.rs
- derive_builder/tests/compile-fail/rename_setter_struct_level.rs
- derive_builder/tests/ignore/no_std.rs
- derive_builder_core/Cargo.toml
Using updates to the Rust compiler and to `darling`, make errors much nicer: They now point to the correct location in `#[builder(...)]` attributes, as seen in the compile-fail tests.
> Improve error experience

- derive_builder/CHANGELOG.md
- derive_builder/README.md
- derive_builder/src/lib.rs
- derive_builder/src/options/darling_opts.rs
- derive_builder/tests/setter_strip_option.rs
- derive_builder_core/src/setter.rs
related to ticket #116 but with some difference against original request (mark with (!)):
- `strip_option` is a flag of setter
-  it can be applied at field or struct level
- (!) unset value is set to None, only if the field is builder is flagged with `default`
- (!) if the flag is applied on non Option<T>, then it is ignored (as it can be set on a struct with non Option field without generate error, less boiler plate to use IMHO, and match my target usage)
see change in lib.rs and test for usage.
> add strip_option to setter

- .travis.yml
- derive_builder/CHANGELOG.md
- derive_builder/Cargo.toml
- derive_builder/README.md
- derive_builder/src/options/darling_opts.rs
- derive_builder_core/Cargo.toml
- derive_builder_core/src/builder.rs
- derive_builder_core/src/setter.rs
There were some changes in how syn handles paths/idents. I haven't actually written any procedural macros myself so somebody may want to look it over, but all tests were passed.
> Update darling, quote, proc-macro2, syn

- dev/deploy.sh
Fixes #146.
Perhaps after fixing #149, it can be tested for real.
> Wait 10s before publishing `derive_builder`.

- derive_builder/Cargo.toml
- derive_builder/src/lib.rs
- derive_builder/src/options/darling_opts.rs
- derive_builder/src/options/mod.rs
- derive_builder/tests/custom_default.rs
- derive_builder/tests/setter_strip_option.rs
- derive_builder_core/Cargo.toml
- derive_builder_core/src/bindings.rs
- derive_builder_core/src/block.rs
- derive_builder_core/src/build_method.rs
- derive_builder_core/src/builder.rs
- derive_builder_core/src/builder_field.rs
- derive_builder_core/src/deprecation_notes.rs
- derive_builder_core/src/initializer.rs
- derive_builder_core/src/lib.rs
- derive_builder_core/src/options.rs
- derive_builder_core/src/setter.rs
I fixed most clippy lints, except the ones from below:
```
Checking derive_builder_core v0.8.0 (/media/hdd/home/projects/rust-derive-builder/derive_builder_core)
error: this argument (1 byte) is passed by reference, but would be more efficient if passed by value (limit: 8 byte)
--> derive_builder_core/src/bindings.rs:12:22
|
12 |     pub fn string_ty(&self) -> Path {
|                      ^^^^^ help: consider passing by value instead: `self`
|
note: lint level defined here
--> derive_builder_core/src/lib.rs:25:9
|
25 | #![deny(warnings, missing_docs)]
|         ^^^^^^^^
= note: `#[deny(clippy::trivially_copy_pass_by_ref)]` implied by `#[deny(warnings)]`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#trivially_copy_pass_by_ref
error: this …
```
> minor improvements

- derive_builder/Cargo.toml
- derive_builder_core/Cargo.toml
This allows `-Z minimal-versions` to be used in derive_builder-using
crates.
---
Needs a release of darling with TedDriggs/darling#83 included. Just making a guess at the version number it would use.
> darling: bump for minimal version compatibility

- derive_builder/src/options/darling_opts.rs
- derive_builder/tests/setter_custom.rs
- derive_builder_core/src/builder_field.rs
- derive_builder_core/src/initializer.rs
- derive_builder_core/src/setter.rs
Implements feature request #110
First I added an option to the `FieldLevelSetter` called `custom`. Such that the attribute is `#[builder(setter(custom))]`.
This option will behave like `skip` but not cause the field to be "skipped" (i.e. replaced with `PhantomData`). This is done by splitting the `enabled` flag into `setter_enabled` and `field_enabled`. `custom` will only cause the setter to be disabled, but not the field.
I'm aware that `custom` is missing for `StructLevelSetter`. To be honest, it's late and I need the feature. I can implement it tomorrow, if necessary :)
Tests are implemented in `tests/setter_custom.rs`.
I just started using this crate today and didn't look to deep into the code and it's capabilities (doc seems to be lacking). So there might be some inter-dependencies I …
> setter(custom) which allows a custom setter implementation

- derive_builder/Cargo.toml
- derive_builder_core/Cargo.toml
- derive_builder_core/src/builder.rs
Closes #160 and fixes #139.
I feature gated this, because I think that this might be useful in the future, if someone wants to see the clippy lints to improve the code.
> Add `#[allow(clippy::all)]` to output

- .travis.yml
- derive_builder/CHANGELOG.md
- derive_builder/Cargo.toml
- derive_builder/README.md
- derive_builder/build/skeptic.rs
- derive_builder/src/lib.rs
- derive_builder/tests/compile-fail/private_build_fn.rs
- derive_builder/tests/compile-fail/private_builder.rs
- derive_builder/tests/compile-fail/rename_setter_struct_level.rs
- derive_builder/tests/compiletests.rs
- derive_builder/tests/try_setter.rs
- derive_builder_core/Cargo.toml
This PR also bumps minimal version from 1.37.0 to 1.40.0. Skeptic and compiler tests require at least 1.38.0 and `#[non_exhaustive]` feature in PR #169 needs at least 1.40.0.
This also closes #140
> Remove nightlytests feature flag. Run all tests on all versions of Rust.

- derive_builder/build/skeptic.rs
- derive_builder/examples/validation.rs
- derive_builder/src/lib.rs
- derive_builder/src/options/darling_opts.rs
- derive_builder/tests/builder_name.rs
- derive_builder/tests/custom_default.rs
- derive_builder/tests/generic_structs.rs
- derive_builder/tests/lifetime.rs
- derive_builder/tests/run-pass/custom_types.rs
- derive_builder/tests/setter_visibility.rs
- derive_builder/tests/try_setter.rs
- derive_builder/tests/validation.rs
- derive_builder_core/src/build_method.rs
- derive_builder_core/src/builder.rs
- derive_builder_core/src/initializer.rs
> Structural error

- derive_builder/Cargo.toml
- derive_builder/tests/compile-fail/deny_empty_default.rs
- derive_builder/tests/compile-fail/deny_empty_default.stderr
- derive_builder/tests/compile-fail/private_build_fn.rs
- derive_builder/tests/compile-fail/private_build_fn.stderr
- derive_builder/tests/compile-fail/private_builder.rs
- derive_builder/tests/compile-fail/private_builder.stderr
- derive_builder/tests/compile-fail/private_fields.rs
- derive_builder/tests/compile-fail/private_fields.stderr
- derive_builder/tests/compile-fail/rename_setter_struct_level.rs
- derive_builder/tests/compile-fail/rename_setter_struct_level.stderr
- derive_builder/tests/compiletests.rs
- derive_builder_core/build/skeptic.rs
I noticed that compiletest_rs is unstable. You need to run `cargo clean` from time to time to make it work. Its error messages are unreadable. Also I noticed that it doesn't work on macos.
Then I found [this](https://github.com/dtolnay/trybuild/issues/13).  :smirk:
I tested this on Linux and macos and it works well.
> Migrate from compiletest_rs to trybuild

- derive_builder/src/lib.rs
Seems the original url https://aturon.github.io/ownership/builders.html is not working anymore. I found a working url on https://web.archive.org.
> Update link to the builders pattern article

- derive_builder/src/lib.rs
Adds a note to the docs to avoid confusion in a scenario like #182.
> Add note about defaults and build_fn(skip)

- derive_builder_core/src/builder.rs
- derive_builder_core/src/builder_field.rs
- derive_builder_core/src/macro_options/darling_opts.rs
Currently the builder uses #[derive(Default)], which adds additional bounds to the type parameters
requiring them to implement Default. This is not required since the fields are all either `Option`
or `PhantomData`, which always have defaults, and means that Builders cannot be instantiated for
non-Default generics.
This commit makes the builder implement Default manually, without any additional bounds.
> Fix requiring generic parameters to implement Default

- .github/workflows/build.yml
- .travis.yml
- derive_builder/CHANGELOG.md
- derive_builder/Cargo.toml
- derive_builder/README.md
- derive_builder/src/lib.rs
- derive_builder_core/Cargo.toml
- derive_builder_core/build/skeptic.rs
- derive_builder_core/src/build_method.rs
- derive_builder_core/src/builder.rs
- derive_builder_core/src/builder_field.rs
- derive_builder_core/src/deprecation_notes.rs
- derive_builder_core/src/initializer.rs
- derive_builder_core/src/lib.rs
- derive_builder_core/src/setter.rs
- derive_builder_macro/Cargo.toml
- derive_builder_macro/src/lib.rs
Following [this comment](https://github.com/colin-kiegel/rust-derive-builder/issues/140#issuecomment-474967436) of @TedDriggs .
> remove logging feature

- derive_builder_core/src/block.rs
- derive_builder_core/src/build_method.rs
- derive_builder_core/src/builder.rs
- derive_builder_core/src/builder_field.rs
- derive_builder_core/src/deprecation_notes.rs
- derive_builder_core/src/doc_comment.rs
- derive_builder_core/src/initializer.rs
- derive_builder_core/src/lib.rs
- derive_builder_core/src/setter.rs
The only crate to depend on derive_builder_core is derive_builder. While it's useful that derive_builder_core is _able_ to export more than the derive function in the future, shrinking the API surface to be only the one function now means that adding builder features won't force semver bumps due to changes in the public-facing intermediate structs.
Because the structs are no longer public, doc-tests for those structs no longer compile. These are now ignored.
> Shrink derive_builder_core's public API

- derive_builder/examples/custom_error.rs
- derive_builder/examples/custom_error_generic.rs
- derive_builder/src/lib.rs
- derive_builder/tests/compile-fail/custom_error_generic_missing_bound.rs
- derive_builder/tests/compile-fail/custom_error_generic_missing_bound.stderr
- derive_builder/tests/compile-fail/custom_error_no_from.rs
- derive_builder/tests/compile-fail/custom_error_no_from.stderr
- derive_builder/tests/custom_default.rs
- derive_builder/tests/run-pass/custom_error_default.rs
- derive_builder_core/src/build_method.rs
- derive_builder_core/src/builder.rs
- derive_builder_core/src/error.rs
- derive_builder_core/src/initializer.rs
- derive_builder_core/src/lib.rs
- derive_builder_core/src/macro_options/darling_opts.rs
@andy128k this is an interesting example of using custom validation errors today. For #181, we'd need a way for this to work without the heap allocation of `String`, which is what's driving #191.
> Custom error example

- derive_builder/tests/setter_extend.rs
- derive_builder_core/src/macro_options/darling_opts.rs
- derive_builder_core/src/setter.rs
> Add an option to extend collection-like fields (`each`-version)

- derive_builder_core/Cargo.toml
- derive_builder_core/src/block.rs
Currently build of the crate is broken. The reason is [this change in `syn`](https://github.com/dtolnay/syn/commit/28915db5f27d64c0bdcf47c57c5d978c82f9e449).
> Fix a test

- .github/workflows/build.yml
- Cargo.toml
- derive_builder/src/lib.rs
- derive_builder_core/src/block.rs
- derive_builder_core/src/builder.rs
- derive_builder_core/src/macro_options/darling_opts.rs
- derive_builder_no_std_tests/Cargo.toml
- derive_builder_no_std_tests/src/main.rs
> Make it work in no_std environment

- derive_builder/README.md
The `alloc` feature became stable.
> docs: remove the obsolete instruction

- derive_builder/CHANGELOG.md
- derive_builder/README.md
- derive_builder/tests/setter_extend.rs
- derive_builder_core/src/lib.rs
- derive_builder_core/src/macro_options/darling_opts.rs
- derive_builder_core/src/options.rs
- derive_builder_core/src/setter.rs
This change is based on #214, allowing collection setters to use `Into` for extension items. This change **is** backward-compatible; both the name and nested form of `each` are supported.
cc @uint @andy128k
> Support setter(each(into))

- derive_builder_core/src/build_method.rs
- derive_builder_core/src/builder.rs
- derive_builder_core/src/builder_field.rs
- derive_builder_core/src/macro_options/darling_opts.rs
- derive_builder_core/src/setter.rs
* Use parse_quote for literals, removing unwraps
* Use format_ident to preserve span data
> Remove all uses of syn::parse_str

- derive_builder/examples/custom_constructor.rs
- derive_builder/tests/custom_constructor.rs
- derive_builder_core/src/builder.rs
- derive_builder_core/src/macro_options/darling_opts.rs
This adds `#[builder(custom_constructor)]` as a way to suppress the generation of `impl Default for FooBuilder`. The name is chosen to avoid confusion with `#[builder(default)]`, as that is about the usage of the struct-level default to fill in missing fields.
One positive emergent property from this is that it's easy to put the `new` method onto the target type, rather than the builder: `ApiClient::new(...)` rather than `ApiClientBuilder::new(...)`. This seems advantageous for managing the set of imports needed to use `ApiClient`.
One unexpected aspect is the need to add `#[builder(setter(custom))]` to each set-up-front field. While it does make the struct more verbose, I think it illustrates how many nuances there are to this behavior, and it ends up supporting the idea that this is …
> Allow opting out of impl Default

- derive_builder/CHANGELOG.md
- derive_builder/tests/forward_allow_attr.rs
- derive_builder_core/src/builder.rs
- derive_builder_core/src/macro_options/darling_opts.rs
If a struct is conditionally present, its builder should only be present in the same conditions.
If a struct disables lints, its builder should disable the same lints.
Fixes #222
> Forward allow and cfg attrs to builder

- derive_builder_core/Cargo.toml
and_then appeared in darling 0.12.4.
Sorry for not spotting htis earlier.
> darling: Bump dependency to 0.12.4

- derive_builder_core/src/macro_options/darling_opts.rs
RFC, as discussed in https://github.com/colin-kiegel/rust-derive-builder/pull/241#issuecomment-1069346362   .  It seemed better to demonstrate it rather than talk in the abstract.
I think it has come out quite nicely.  In particular, removing the duplicated specification of the output field variables now means it's not possible to accidentally get the unnesting and copying information out of step.
But if you prefer the code the way it is, please do feel free to say so and just close this MR.
> Break out distribute_and_unnest_attrs

- .github/workflows/build.yml
- derive_builder/Cargo.toml
- derive_builder/tests/compile-fail/builder_setter_attr.stderr
- derive_builder/tests/compile-fail/custom_error_generic_missing_bound.stderr
- derive_builder/tests/compile-fail/custom_error_no_from.stderr
- derive_builder/tests/compile-fail/private_build_fn.stderr
- derive_builder/tests/compile-fail/private_builder.stderr
- derive_builder/tests/compile-fail/private_fields.stderr
- derive_builder/tests/compile-fail/rename_setter_struct_level.stderr
- derive_builder/tests/compiletests.rs
This version works locally on M1 processors.
> Move compile-fail tests to rustc 1.59

- derive_builder_core/Cargo.toml
- derive_builder_core/src/macro_options/darling_opts.rs
- derive_builder_macro/Cargo.toml
This lets us use:
* Faster compilation times courtesy of quote 1.0.18
* Implicit defaulting behavior of darling 0.14.0
* Updated `Flag` struct from darling 0.14.0
> Update darling, proc-macro2, quote, and syn

- derive_builder/CHANGELOG.md
- derive_builder/tests/compile-fail/vis_conflict.rs
- derive_builder/tests/compile-fail/vis_conflict.stderr
- derive_builder_core/src/build_method.rs
- derive_builder_core/src/builder.rs
- derive_builder_core/src/builder_field.rs
- derive_builder_core/src/macro_options/darling_opts.rs
- derive_builder_core/src/setter.rs
* Use Cow&lt;syn::Visibility> to avoid unnecessary cloning
* Make as_expressed_vis return a Result
* Add Visibility::explicit
This will be updated for #246 soon.
> Add restricted visibility support to builders, build methods, setters, and fields

- derive_builder/CHANGELOG.md
- derive_builder/tests/compile-fail/builder_field_custom.rs
- derive_builder/tests/compile-fail/builder_field_custom.stderr
- derive_builder_core/src/macro_options/darling_opts.rs
If `field.type` is used without `field.build`, a Move conversion is used instead of the OptionOrDefault conversion. This means that the presence of `field.type` prevents a field-level `default` from doing anything. Standard practice in derive_builder is to produce an error when parameters are not going to be used.
Fixes #269
> Produce error for `default` with `field.type`

- derive_builder_macro/src/lib.rs
I'm pretty sure this was originally done to emulate `serde`, but `serde` has traits that match the name of its derive macros so the hiding makes more sense there.
> Don't hide the Builder macro in docs

- derive_builder/Cargo.toml
- derive_builder/tests/dummy-crate/Cargo.toml
- derive_builder_core/Cargo.toml
- derive_builder_macro/Cargo.toml
The new recommendation is to follow the SPDX 2.1 standard. This allows automatic license verification software to work properly. Reference: https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields
> Update license field following SPDX 2.1 license expression standard

- derive_builder/CHANGELOG.md
- derive_builder/tests/setter_custom.rs
- derive_builder/tests/try_setter.rs
- derive_builder_core/src/setter.rs
> Adds a check for `strip_option` when using `try_setter`

- derive_builder_core/src/change_span.rs
- derive_builder_no_std_tests/src/lib.rs
This is causing a clippy violation that is making CI fail.
> Remove unnecessary into_iter()

- .github/workflows/build.yml
- Cargo.toml
- derive_builder/CHANGELOG.md
- derive_builder/Cargo.toml
- derive_builder/README.md
- derive_builder/src/lib.rs
- derive_builder/tests/compile-fail/build_fn_error.rs
- derive_builder/tests/compile-fail/build_fn_error.stderr
- derive_builder_core/Cargo.toml
- derive_builder_core/src/builder.rs
- derive_builder_core/src/macro_options/darling_opts.rs
- derive_builder_macro/Cargo.toml
- derive_builder_no_alloc_tests/Cargo.toml
- derive_builder_no_alloc_tests/src/lib.rs
- derive_builder_no_std_tests/Cargo.toml
Currently, using `derive_builder` in `no_std` still forces the user to make a `global_allocator` since the crate links against `alloc`. This PR tries to avoid that in two aways.
* Create a new feature flag `alloc` that controls whether the `alloc` crate is used. This allows `no_std` user to opt into using allocation if they want it.
* New `build_fn` field, `validation_error: bool` that controls whether the generated error includes `ValidationError(String)`. This prevents usage of any `alloc` code but also limits the user from using the `validate` field.
* The user can provide a custom `build_fn` `error` to avoid `alloc` code from being used.
This is to fix issue: https://github.com/colin-kiegel/rust-derive-builder/issues/303.
> Allows prevention of `alloc` dependency through feature and disabling of `ValidationError(String)` variant.

- derive_builder/CHANGELOG.md
- derive_builder/src/lib.rs
- derive_builder/tests/builder_field_custom.rs
- derive_builder/tests/compile-fail/builder_field_custom.rs
- derive_builder/tests/compile-fail/builder_field_custom.stderr
- derive_builder_core/src/macro_options/darling_opts.rs
On syn 2.0, field(type = "...") will break with a not-very-informative error message.
While we can't prevent that, we can make it possible for people to switch to the new property name without needing to change anything else, so that the eventual dependency version bump is fully source-compatible.
I debated using `DeprecationNotes` to put a warning on all uses of `type`, but decided it wasn't worth the code churn necessary to plumb that through from the options area all the way to code generation. This is already a highly specialized feature, and the fix is pretty easy once you read the release notes.
> Accept field(ty = "...") to ease migration to syn 2.0

- derive_builder/Cargo.toml
- derive_builder/src/lib.rs
- derive_builder/tests/builder_field_custom.rs
- derive_builder/tests/compile-fail/builder_field_custom.rs
- derive_builder/tests/compile-fail/builder_field_custom.stderr
- derive_builder/tests/compile-fail/crate_root.stderr
- derive_builder_core/Cargo.toml
- derive_builder_core/src/block.rs
- derive_builder_core/src/build_method.rs
- derive_builder_core/src/builder.rs
- derive_builder_core/src/builder_field.rs
- derive_builder_core/src/default_expression.rs
- derive_builder_core/src/deprecation_notes.rs
- derive_builder_core/src/initializer.rs
- derive_builder_core/src/macro_options/darling_opts.rs
- derive_builder_core/src/setter.rs
- derive_builder_macro/Cargo.toml
This uses the most recent major version of `syn`, as well as the most recent version of `darling`.
1. It's no longer possible to use `type` to override the type of a field; instead, `ty` must be used.
Fixes #292
> Update to syn 2 and darling 0.20.5

- derive_builder/tests/try_setter.rs
- derive_builder_core/src/block.rs
- derive_builder_core/src/builder.rs
- derive_builder_core/src/macro_options/darling_opts.rs
New warnings in nightly since https://github.com/rust-lang/rust/pull/117772. With `deny(warnings)`, this is causing CI to fail.
```console
error: the item `syn` is imported redundantly
--> derive_builder_core/src/block.rs:5:11
|
5  | use syn::{self, spanned::Spanned, Block, LitStr};
|           ^^^^
|
::: derive_builder_core/src/lib.rs:27:1
|
27 | extern crate syn;
| ----------------- the item `syn` is already imported here
|
note: the lint level is defined here
--> derive_builder_core/src/lib.rs:18:9
|
18 | #![deny(warnings, missing_docs)]
|         ^^^^^^^^
= note: `#[deny(unused_imports)]` implied by `#[deny(warnings)]`
error: the item `syn` is imported redundantly
--> derive_builder_core/src/builder.rs:6:11
|
6  | use syn::{self, Path, TraitBound, TraitBoundModifier, TypeParamBound}; …
```
> Resolve prelude redundant import warnings in nightly

- derive_builder_core/Cargo.toml
- derive_builder_core/src/macro_options/darling_opts.rs
Before darling 0.20.8, the receiver struct had to take the forwarded attributes without transformation. That led to the options structs having a field called attrs that was drained during FromDeriveInput/FromField execution, and was vestigial on the finished struct.
The new approach instead does that transformation in the attrs field, resulting in an emitted type that is cleaner and more obvious to use.
> Use darling's `with` to handle unnesting attrs

- derive_builder/src/lib.rs
It got stabilised in 2019, I think it's safe to remove the caveat by now.  :stuck_out_tongue_winking_eye:
> Don't refer to TryInto as not-yet-stable

- derive_builder/src/lib.rs
- derive_builder/tests/run-pass/default_typeparams.rs
- derive_builder_core/src/builder.rs
- derive_builder_core/src/macro_options/darling_opts.rs
- derive_builder_no_alloc_tests/src/lib.rs
the derived builder doesn't offer the same default types as the source struct. that forces the user to explicit all types when theses can't be infered.
in the case I have, I want to derive a builder on a struct with a bunch of callbacks:
```rust
pub struct Settings<T, S = fn(T), R = fn(T), C = fn(T)>
where S: FnOnce(T), R: FnMut(T), C: FnMut(T)
```
on which I only need to specific `T` when instanciating `Settings` "by hand". but when using the derived builder, I need to specifiy *all* the types (which is especially cumbersome as most of theses callbacks are optional).
there was a confusion in the implementation between generics meant for the builder struct (which [can contain default types](https://doc.rust-lang.org/book/ch19-03-advanced-traits.html#default-generic-type-parameters-and-oper …
> forward default typeparam
